name: Bandit
on:
  push:
    branches:
      - "*" # This will trigger the workflow on all branches
  pull_request:
    branches:
      - "*" # This will trigger the workflow on all branches
  schedule:
    - cron: '00 12 * * 0'

jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Branch Name
        id: branch_name
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | sed 's/refs\/heads\///')"
        
      - name: Bandit Scan
        id: bandit
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with: # optional arguments
          exit_zero: true # optional, default is DEFAULT
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information.
        
      # Download the SARIF artifact generated by Bandit
      - name: Download SARIF artifact
        uses: actions/download-artifact@v2
        with:
          name: results.sarif # This should match the name of the artifact you want to download
      
      - name: Send To Discord Webhook
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "Bandit Workflow"
          avatar-url: "https://github.com/KillaMeep/inventory-system/blob/main/icons/bot-icon.png?raw=true"
          content: "Bandit Output for branch: ${{ steps.branch_name.outputs.branch }}"
          filename: results.sarif
